# HTTP: редирект на HTTPS
server {
    listen 80;
    server_name app.tero.design;
    return 301 https://$host$request_uri;
}

# HTTPS + Let's Encrypt
server {
    listen 443 ssl;
    server_name app.tero.design;

    ssl_certificate     /etc/letsencrypt/live/app.tero.design/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.tero.design/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 200M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
